def image

pipeline {
    agent any 
    stages {
        stage('build') {
            steps {
                echo "running in $WORKSPACE"
                dir("$WORKSPACE/nodejs-docker") {
                script {
                    image = docker.build("dhaasarathy/node:v1")
                }
            }
        }
        }
        stage('test') {
            steps {
                script {
                    container = image.run()
                    container.stop()
                }
            }
        }
        stage('deploy') {
            steps{
                echo "image pushed to hub"
                script {
                    image.push()
                }
            }
        }
    }
}